package epam.java.controller;

public enum ChoiceItems {
    PRINT, PRINT_TOTAL_WEIGHT, SORT_BY_WEIGHT, SORT_BY_SUGAR_CONTENT, SORT_BY_PRODUCER, SORT_BY_NAME,SELECT_BY_NAME, SELECT_BY_PRODUCER,
    SELECT_BY_SUGAR_CONTENT,SELECT_BY_WEIGHT, SELECT_CANDIES, SELECT_CHOCOLATE, SELECT_COOKIES,
    SELECT_CANDIES_BY_TASTE, SELECT_CANDIES_BY_CATEGORIE, SELECT_CHOCOLATE_WITH_NUTS, SELECT_CHOCOLATE_WITH_RAISINS,
    SELECT_CHOCOLATE_WITH_FRUITS, SELECT_CHOCOLATE_BY_PERCENT_OF_COCOA, SELECT_COOKIES_BY_QUANTITY, SELECT_COOKIES_BY_CATEGORIE,
    DELETE_FILTERS, EXIT
}
